### PR TITLE
fix: change quote from ‘’ to `'

### PR DESCRIPTION
**Pull request by ShuguangSun**
change quote from ‘’ to `' in doc

### CODE REVIEW

**Comment by twlz0ne** [comment]
Thanks for the pr.

But I think `‘’` and <code>`'</code> are both legal:

https://github.com/emacs-mirror/emacs/blob/4a94881345819dd68062bc729b5b7ddeab00041b/lisp/emacs-lisp/lisp-mode.el#L501
 
```elisp
;; Words inside ‘’ and `' tend to be symbol names.
```

Some other examples:

```sh
⋊> [~/r/emacs-melpa] rg '‘[[:alnum:]\-]+’' ~/scratch/build-emacs/emacs-28/lisp/ -g '*.el'
......
~/scratch/build-emacs/emacs-28/lisp/subr.el
155:set earlier in the ‘setq-local’.  The return value of the
156:‘setq-local’ form is the value of the last VALUE.

~/scratch/build-emacs/emacs-28/lisp/window.el
9237:  ;; Process lines as returned by ‘window-lines-pixel-dimensions’.

~/scratch/build-emacs/emacs-28/lisp/cedet/mode-local.el
50:;; ‘require’ by (defvar find-function-regexp-alist) and
724:      ;; don't want to list the same function twice. So order ‘modes’
......
```

BTW, after you forked the code, I performed a force push. Sorry for that.

**Comment by ShuguangSun** [comment]
Got it. Thanks for the information.

**Comment by twlz0ne** [comment]
Hi,
If you don't mind, I will close this PR.

**Comment by ShuguangSun** [comment]
Please close it.

**Pull request closed without merging**
