### PR TITLE
Add support for typescript

### PR DESCRIPTION
**Pull request by terlar**
Add typescript mode and add the "`" quote character to javascript as well.

### CODE REVIEW

**Comment by terlar** [comment]
Seems the CI have some issues running tests for Emacs 25.1

**Comment by twlz0ne** [comment]
Seems there is a bug in `font-lock-ensure` of Emacs 25.1.

Reproduce:

```sh
⋊> emacs-25.1 --batch --eval "(with-temp-buffer
                                (python-mode)
                                (insert \"    '''dosctring'''\")
                                (font-lock-mode 1)
                                (font-lock-ensure))"
```

Also reported in 27.0 https://lists.gnu.org/archive/html/bug-gnu-emacs/2018-12/msg00602.html

**Comment by twlz0ne** [comment]
Could you please rebase this PR on the latest master branch?

**Comment by terlar** [comment]
Done, thank you

**Pull request merged**
